version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context: tanuki-keyword
jobs:
  build:
    docker:
      - image: s3848845/sep-frontend
        auth: 
            username: s3848845
            password: $DOCKERHUB_PASS
    steps:
      - checkout
      - run:
          name: get the docker client
          command: apk add docker-cli
      - setup_remote_docker:
          version: 20.10.6
      - run: 
          name: login to docker
          command: |
            echo $DOCKERHUB_PASS | docker login -u s3848845 --password-stdin
      - run:
          name: build image
          command: cd SEPT2021_MajorProject && docker build --file=FrontEnd/myfirstapp/frontend.dockerfile -t s3848845/sep-frontend:latest .

      - run:
          name: publish to dockerhub
          command: |
            docker push s3848845/sep-frontend:latest
