export const GET_ERRORS = "GET_ERRORS";
export const GET_PERSONS = "GET_PERSONS";
export const GET_PERSON = "GET_PERSON";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const SET_PUBREQUEST = "SET_PUBREQUEST";
export const UPDATE_USER= "UPDATE_USER";
export const GET_PUBUSERS= "GET_PUBUSERS";

export const GET_BOOK = "GET_BOOK";
export const SAVE_BOOK_REQUEST = "SAVE_BOOK_REQUEST";
export const FETCH_BOOK_REQUEST = "FETCH_BOOK_REQUEST";
export const UPDATE_BOOK_REQUEST = "UPDATE_BOOK_REQUEST";
export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const BOOK_SUCCESS = "BOOK_SUCCESS";
export const BOOK_FAILURE = "BOOK_FAILURE";

export const FETCH_LANGUAGES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const LANGUAGES_FAILURE = "LANGUAGES_FAILURE";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_FAILURE = "GENRES_FAILURE";

export const CREATE_REQ = "CREATE_REQ";
export const DELETE_REQ = "DELETE_REQ";
export const GET_REQ = "GET_REQS";
